# Generated by Django 4.1.6 on 2023-02-05 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0)),
                ('code', models.PositiveIntegerField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('time_create', models.DateField(auto_now_add=True)),
                ('time_update', models.DateField(auto_now=True)),
                ('img', models.ImageField(default=None, upload_to='uploads/%Y/%m/%d/')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.group')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=200)),
                ('time_create', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
